---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: ansible-role-xfce-debian-10
    image: debian:10
  - name: ansible-role-xfce-debian-11
    image: debian:11
  - name: ansible-role-xfce-ubuntu-2004
    image: ubuntu:20.04
  - name: ansible-role-xfce-ubuntu-2204
    image: ubuntu:22.04

provisioner:
  name: ansible

verifier:
  name: testinfra
